// Medical AI Agent - Simple rule-based system with structured conversation
export interface MedicalQuestion {
  question: string;
  type: 'text' | 'multiple';
  options?: string[];
}

export interface MedicalReport {
  symptoms: string[];
  duration: string;
  severity: string;
  additionalInfo: string;
  recommendations: string[];
  disclaimer: string;
}

const conversationFlow: MedicalQuestion[] = [
  {
    question: "Of course, I'm here to help. Could you please tell me what symptoms you're experiencing?",
    type: 'text'
  },
  {
    question: "How long have you been experiencing these symptoms?",
    type: 'multiple',
    options: ['Less than 24 hours', '1-3 days', '4-7 days', 'More than a week', 'More than a month']
  },
  {
    question: "On a scale of 1-10, how would you rate the severity of your symptoms? (1 being mild, 10 being severe)",
    type: 'multiple',
    options: ['1-3 (Mild)', '4-6 (Moderate)', '7-9 (Severe)', '10 (Critical)']
  },
  {
    question: "Is there anything else you'd like to mention? (Medical history, allergies, current medications, etc.)",
    type: 'text'
  }
];

export function getNextQuestion(messageCount: number): string | null {
  const questionIndex = Math.floor(messageCount / 2);
  if (questionIndex < conversationFlow.length) {
    return conversationFlow[questionIndex].question;
  }
  return null;
}

export function generateMedicalReport(messages: { role: string; content: string }[]): MedicalReport {
  const userMessages = messages.filter(m => m.role === 'user');
  
  const symptoms = userMessages[0]?.content || 'Not specified';
  const duration = userMessages[1]?.content || 'Not specified';
  const severity = userMessages[2]?.content || 'Not specified';
  const additionalInfo = userMessages[3]?.content || 'None';
  
  // Generate recommendations based on severity
  let recommendations: string[] = [];
  
  if (severity.includes('Critical') || severity.includes('Severe')) {
    recommendations = [
      'Seek immediate medical attention at an emergency room',
      'Do not wait for symptoms to worsen',
      'Call emergency services if symptoms are life-threatening',
      'Bring a list of current medications and allergies'
    ];
  } else if (severity.includes('Moderate')) {
    recommendations = [
      'Schedule an appointment with your primary care physician within 24-48 hours',
      'Monitor your symptoms closely',
      'Keep a symptom diary with dates and severity',
      'Avoid strenuous activities until evaluated by a doctor',
      'Stay hydrated and get adequate rest'
    ];
  } else {
    recommendations = [
      'Monitor your symptoms over the next few days',
      'Schedule a routine appointment with your doctor if symptoms persist',
      'Get adequate rest and stay hydrated',
      'Maintain a healthy diet',
      'Consider over-the-counter remedies appropriate for your symptoms'
    ];
  }
  
  return {
    symptoms: [symptoms],
    duration,
    severity,
    additionalInfo,
    recommendations,
    disclaimer: 'This report is generated by an AI assistant and should not replace professional medical advice. Always consult with a qualified healthcare provider for proper diagnosis and treatment.'
  };
}

export async function getMedicalResponse(userMessage: string, messageHistory: any[]): Promise<string> {
  // Simple rule-based responses
  const nextQuestion = getNextQuestion(messageHistory.length);
  
  if (nextQuestion) {
    return nextQuestion;
  } else {
    return "Thank you for providing all the information. I've generated a comprehensive medical report based on our conversation. You can download it as a PDF for your records and to share with your healthcare provider.";
  }
}

