// Medical AI Agent - Client-side wrapper for API calls
export interface MedicalReport {
  symptoms: string[];
  duration: string;
  severity: string;
  additionalInfo: string;
  recommendations: string[];
  disclaimer: string;
}

// Client-side function that calls the API route
export async function getMedicalResponseWithGroq(
  userMessage: string, 
  messageHistory: Array<{ role: string; content: string }>
): Promise<string> {
  
  try {
    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: userMessage,
        messageHistory: messageHistory
      })
    });

    if (!response.ok) {
      throw new Error('API request failed');
    }

    const data = await response.json();
    
    // Log which mode is being used (optional, for debugging)
    if (data.mode === 'groq-ai') {
      console.log('✅ Using Groq AI');
    } else {
      console.log('ℹ️ Using rule-based system');
    }
    
    return data.response;
    
  } catch (error) {
    console.error('Error calling chat API:', error);
    
    // Fallback to basic response on error
    return "I apologize, but I'm having trouble connecting. Could you please try again?";
  }
}

export function generateMedicalReport(messages: { role: string; content: string }[]): MedicalReport {
  const userMessages = messages.filter(m => m.role === 'user');
  
  // Extract information from conversation
  let symptoms = 'Not specified';
  let duration = 'Not specified';
  let severity = 'Not specified';
  let additionalInfo = 'None';
  
  // Try to intelligently parse the conversation
  if (userMessages.length >= 1) {
    symptoms = userMessages[0]?.content || 'Not specified';
  }
  if (userMessages.length >= 2) {
    duration = userMessages[1]?.content || 'Not specified';
  }
  if (userMessages.length >= 3) {
    severity = userMessages[2]?.content || 'Not specified';
  }
  if (userMessages.length >= 4) {
    additionalInfo = userMessages[3]?.content || 'None';
  }
  
  // Generate recommendations based on severity
  let recommendations: string[] = [];
  
  const severityLower = severity.toLowerCase();
  
  if (severityLower.includes('10') || severityLower.includes('critical') || severityLower.includes('severe') || severityLower.includes('9') || severityLower.includes('8') || severityLower.includes('7')) {
    recommendations = [
      'Seek immediate medical attention at an emergency room or urgent care',
      'Do not wait for symptoms to worsen',
      'Call emergency services (911) if symptoms are life-threatening',
      'Bring a list of current medications, allergies, and medical history',
      'Have someone accompany you if possible'
    ];
  } else if (severityLower.includes('moderate') || severityLower.includes('6') || severityLower.includes('5') || severityLower.includes('4')) {
    recommendations = [
      'Schedule an appointment with your primary care physician within 24-48 hours',
      'Monitor your symptoms closely and note any changes',
      'Keep a symptom diary with dates, times, and severity',
      'Avoid strenuous activities until evaluated by a doctor',
      'Stay well hydrated and get adequate rest',
      'Take over-the-counter medications only as directed'
    ];
  } else {
    recommendations = [
      'Monitor your symptoms over the next few days',
      'Schedule a routine appointment with your doctor if symptoms persist or worsen',
      'Get adequate rest and maintain good sleep hygiene',
      'Stay well hydrated throughout the day',
      'Maintain a healthy, balanced diet',
      'Consider appropriate over-the-counter remedies for symptom relief',
      'Avoid known triggers or aggravating factors'
    ];
  }
  
  return {
    symptoms: [symptoms],
    duration,
    severity,
    additionalInfo,
    recommendations,
    disclaimer: 'This report is generated by an AI assistant and should not replace professional medical advice. Always consult with a qualified healthcare provider for proper diagnosis and treatment. In case of emergency, call 911 or go to the nearest emergency room immediately.'
  };
}

