import jsPDF from 'jspdf'
import type { MedicalReport } from './medical-ai'

export function generatePDF(report: MedicalReport, patientName: string, consultationDate: Date) {
  const doc = new jsPDF()
  
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - (margin * 2)
  let yPosition = 20

  // Title
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('Medical Consultation Report', margin, yPosition)
  yPosition += 15

  // Subtitle
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text('MediConsult AI - Intelligent Medical Consultation', margin, yPosition)
  yPosition += 15

  // Patient Information
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('Patient Information', margin, yPosition)
  yPosition += 8

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`Name: ${patientName}`, margin, yPosition)
  yPosition += 6
  doc.text(`Date: ${new Date(consultationDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })}`, margin, yPosition)
  yPosition += 12

  // Symptoms
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Reported Symptoms', margin, yPosition)
  yPosition += 8

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  const symptomsText = report.symptoms.join(', ')
  const symptomLines = doc.splitTextToSize(symptomsText, maxWidth)
  doc.text(symptomLines, margin, yPosition)
  yPosition += (symptomLines.length * 6) + 8

  // Duration
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Duration', margin, yPosition)
  yPosition += 8

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(report.duration, margin, yPosition)
  yPosition += 12

  // Severity
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Severity Level', margin, yPosition)
  yPosition += 8

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(report.severity, margin, yPosition)
  yPosition += 12

  // Additional Information
  if (report.additionalInfo && report.additionalInfo !== 'None') {
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Additional Information', margin, yPosition)
    yPosition += 8

    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    const additionalLines = doc.splitTextToSize(report.additionalInfo, maxWidth)
    doc.text(additionalLines, margin, yPosition)
    yPosition += (additionalLines.length * 6) + 8
  }

  // Check if we need a new page
  if (yPosition > 250) {
    doc.addPage()
    yPosition = 20
  }

  // Recommendations
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Recommendations', margin, yPosition)
  yPosition += 8

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  report.recommendations.forEach((rec, index) => {
    const recText = `${index + 1}. ${rec}`
    const recLines = doc.splitTextToSize(recText, maxWidth)
    
    // Check if we need a new page
    if (yPosition + (recLines.length * 6) > 270) {
      doc.addPage()
      yPosition = 20
    }
    
    doc.text(recLines, margin, yPosition)
    yPosition += (recLines.length * 6) + 4
  })

  yPosition += 8

  // Check if we need a new page for disclaimer
  if (yPosition > 240) {
    doc.addPage()
    yPosition = 20
  }

  // Disclaimer
  doc.setFillColor(255, 243, 224)
  doc.rect(margin - 5, yPosition - 5, maxWidth + 10, 35, 'F')
  
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(180, 83, 9)
  doc.text('Important Disclaimer', margin, yPosition + 2)
  yPosition += 8

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(120, 53, 15)
  const disclaimerLines = doc.splitTextToSize(report.disclaimer, maxWidth)
  doc.text(disclaimerLines, margin, yPosition)

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.setFont('helvetica', 'normal')
    doc.text(
      `Page ${i} of ${pageCount} - Generated by MediConsult AI`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  }

  // Save the PDF
  const fileName = `medical-report-${new Date().getTime()}.pdf`
  doc.save(fileName)
}

